# TEAM 2 — DATA UNDERSTANDING & PROFILING


1. CHOSEN DATASET SELECTION
--------------------------------------------------------------------------------
After evaluating multiple choices based on clarity and ease for beginners,
the "Credit Risk Dataset" was selected as the optimal choice.

* Why this dataset?
  - It has a well-defined target column (loan_status).
  - It contains intuitive and clean features.
  - Suitable for basic profiling and Machine Learning training.


2. DATASET OVERVIEW & BRIEF DESCRIPTION
--------------------------------------------------------------------------------
The Credit Scoring Dataset evaluates the creditworthiness of individuals based
on demographic, financial, and behavioral attributes. It helps financial
institutions mitigate risks and make data-driven lending decisions.

* Data Source: https://www.kaggle.com/datasets/laotse/credit-risk-dataset?resource=download
* Total Instances (Rows): 32,581
* Total Attributes (Columns): 12 (11 Features + 1 Target)


3. DATA DICTIONARY
--------------------------------------------------------------------------------
Below is the definition and structural role of each column in the dataset:

- person_age                  [Integer]     : Age of the loan applicant.
- person_income               [Integer/Float]: Annual income of the applicant.
- person_home_ownership       [Categorical] : Home status (RENT, OWN, MORTGAGE, OTHER).
- person_emp_length           [Float]       : Length of employment in years.
- loan_intent                 [Categorical] : Purpose of the loan (PERSONAL, MEDICAL, etc).
- loan_grade                  [Categorical] : Credit grade assigned to the loan (A–G).
- loan_amnt                   [Integer/Float]: Total amount of the loan requested.
- loan_int_rate               [Float]       : Interest rate applied to the loan.
- loan_status                 [Binary (0/1)]: TARGET VARIABLE (1 = default, 0 = fully paid).
- loan_percent_income         [Float]       : Ratio of loan amount to annual income.
- cb_person_default_on_file   [Categorical] : Historical record of prior default (Y/N).
- cb_person_cred_hist_length  [Integer]     : Length of applicant's credit history (years).


4. BASIC DATA PROFILING & QUALITY ASSESSMENT
--------------------------------------------------------------------------------
A. MISSING VALUES (NULLS):
   - ' person_emp_length ': Has missing entries (needs imputation or handling).
   - ' loan_int_rate ': Has missing interest rates (requires treatment before ML).

B. DUPLICATE ROWS:
   - A check for complete duplicate records will be executed.
   - Any identical rows will be dropped to prevent bias.

C. PRE-PROCESSING OBSERVATIONS:
   - Numerical columns (like age/income) need outlier checks.
   - The target column 'loan_status' will be inspected for class imbalance.

   """
5. PROPOSED MACHINE LEARNING MODELS
--------------------------------------------------------------------------------
Since the target variable 'loan_status' is Binary (0 or 1), this is a
Binary Classification problem. We recommend evaluating the following models:

1. Logistic Regression:
   - A great baseline model for financial risk, easy to interpret and explain
     to stakeholders.
2. Random Forest Classifier:
   - Excellent for handling non-linear relationships and interactions
     between features (like income vs. loan amount).
3. XGBoost / LightGBM:
   - Advanced boosting algorithms that usually give the highest predictive
     accuracy for tabular financial data and handle missing values well.

## <a id='toc1_3_'></a>[Import Libraries](#toc0_)

In [8]:

# 1. to handle the data
import pandas as pd
import numpy as np

## <a id='toc1_4_'></a>[Load the Data](#toc0_)

In [10]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"ayamostafaali","key":"d6d39fb28fa3b76b55002b6b90dbb2a4"}'}

In [11]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [12]:
!kaggle datasets list

ref                                                                     title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
laveshjadon/ai-impact-on-students                                       Impact of Ai on Students                               1187170  2026-05-10 23:12:10.070000           5788        147                1
muhammadwaqas023/ai-impact-in-future-on-jobs-market-in-2030             Ai Impact in future on jobs market in 2030              108338  2026-05-24 15:12:54.047000           1690         40                1
emirhanakku/e-commerce-order-risk-classification-dataset                E-Commerce Order Risk Classification Dataset            360389  2026-05-26 02:56:16.513000            873         29                1
sanyamdhadiwal2302/netflix-data                                         Netflix Data                                           1783607  2026-05-22 18:10:36.380000           1638         41        0.9411765
divyjain28/superstore-sales                                             Superstore Sales Analysis                              1579499  2026-05-15 08:16:38.500000           1194         30                1
laveshjadon/ai-impact-on-human-mental-growth                            Impact of Ai on Human Mental Growth                    3323782  2026-05-23 09:36:48.597000            414         23                1
sergionefedov/dubai-real-estate-sales-and-rentals-20202026              Dubai Real Estate: Sales & Rentals (2020–2026)         4078773  2026-05-09 21:57:40.527000            736         24                1
abbas829/global-superstore-sales-dataset                                Global Superstore Sales Dataset                        2814050  2026-05-23 00:41:54.710000            765         23                1
meruvakodandasuraj/video-game-sales-and-metacritic-intelligence-198026  Video Game Sales & Metacritic Intelligence 1980–26     2477396  2026-05-28 05:04:49.980000            874         30                1
shambhurajejagadale/student-performance-prediction-dataset              Student Performance Prediction Dataset                   84282  2026-05-09 15:49:58.877000           3732         89                1
algozee/teenager-menthal-healy                                          Social Media Impact on Teen Mental Health                16190  2026-04-05 08:04:21.823000          37170        765                1
zynicide/wine-reviews                                                   Wine Reviews                                          53336293  2017-11-27 17:08:04.700000         354276       3871        0.7941176
hideyukizushi/sgkfk-202604041716                                        SGKF|K-202604041716                                   23651366  2026-04-04 10:36:36.847000            330          3        0.5882353
nolanbconaway/pitchfork-data                                            18,393 Pitchfork Reviews                              34891456  2017-01-13 04:18:10.113000          17997        459        0.7058824
rishikeshjani/perch-onnx-for-birdclef-2026                              Perch-onnx-for-birdclef+2026                         395240323  2026-03-30 07:07:25.863000           1972         20       0.47058824
datasnaek/youtube-new                                                   Trending YouTube Video Statistics                    210575746  2019-06-03 00:56:47.177000         305759       5929        0.7941176
jpmiller/publicassistance                                               US Public Food Assistance 1 - WIC                       304041  2023-04-17 20:01:05.960000          26400        511        0.9411765
nasa/kepler-exoplanet-search-results                                    Kepler Exoplanet Search Results                        1215549  2017-10-10 18:26:59.497000          23018        861        0.8235294
rtatman/188-million-us-wildfires                                        1.88 Million US Wildfires                            176270559  2020-05-12 21:03:49.213000          44403       1434        0.8235294
residentmario/things-on-reddit                                          Things on Reddit                                      16773230  2017-10-26 14:10:15.157000          16209        322        0.5882353

In [14]:
!kaggle datasets download -d laotse/credit-risk-dataset

Dataset URL: https://www.kaggle.com/datasets/laotse/credit-risk-dataset
License(s): CC0-1.0
Downloading credit-risk-dataset.zip to /content
100% 368k/368k [00:00<00:00, 96.0MB/s]

In [15]:
import zipfile

with zipfile.ZipFile("credit-risk-dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

In [16]:
df = pd.read_csv("data/credit_risk_dataset.csv")
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

## <a id='toc1_5_'></a>[Data Inspection](#toc0_)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [18]:
df.shape

(32581, 12)

In [19]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [20]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64